### ISSUE TITLE
Issues to maybe close?

### ISSUE THREAD

**Issue by future-highway** [aurae-runtime/aurae#123]
Scanning over the open GH issues, I think there are some that we can possibly close. So naturally, I'm opening another issue to document the ones that may be ready to close.

Probably outdated due to Deno being JS/TS?
- #67 
- #66 
- #6  -> Does JSON.stringify cover this?

ts-proto (Proto -> Typescript generator) includes the docs from the proto files for us:
- #63 

Warnings are breaking the builds, but we may not have completed activating the lints we want:
- #54 

Do we still have this issue?
- #53 

Other:
- #32

**Comment by krisnova** [comment]
Cleaned up these and a few others! Thank you for doing this!
