### ISSUE TITLE
Speed up Auraescript compiles

### ISSUE THREAD

**Issue by future-highway** [aurae-runtime/aurae#127]
Auraescript takes too long to compile. I suspect it has to do with the build.rs doing too much each time, specifically redundant npm calls.

**Comment by neoeinstein** [comment]
This is also likely to be resolved by #129, in addition to dropping the `npm` dependency to build `auraescript`.

**Comment by future-highway** [comment]
If we can drop `npm` via #129, we will also resolve #122.
