### ISSUE TITLE
Unwrap

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#16]
As we are still in the sandbox phase of building Aurae we are using `unwrap` statements in the code. We should replace these with safer and more idiomatic systems in Rust.

Additionally we should build a linting system that prevents code like this from entering the project.

**Comment by future-highway** [comment]
[Clippy](https://github.com/rust-lang/rust-clippy#clippy) is the linter in Rust. It can even be turned on in Clion, which definitely helped my learn more idiomatic rust.

The "unwrap_used" [rule](https://rust-lang.github.io/rust-clippy/rust-1.63.0/index.html#unwrap_used) would be the one for this case, but there are[ many more](https://rust-lang.github.io/rust-clippy/rust-1.63.0/index.html) rules that can be configured to the project's preferences.

Also, allowing unwrap in tests is not considered an issue, as far as I'm aware, and they even include a configuration variable to deny  the use of unwrap generally, but allow it in tests.

**Comment by kris-nova** [comment]
Would you care to implement this in the Makefile? We can add it to the build.

I think a `make ci` target which would then reference a `test` and a `lint` would make the most sense.

**Comment by future-highway** [comment]
We have set clippy to warn on unwrap are now breaking the build on warnings. Related issue #54
