### ISSUE TITLE
Introduce namespaces to cells

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#174]
Should we consider isolating an Aurae cell at the namespace level as well? If so what are the sane defaults we should assume for every Aurae cell? Which namespaces should we consider, and what do we do given the various kernels and their support and awareness of each namespace?

**Comment by dmah42** [comment]
yes we should isolate at the namespace level for each Cell.  

* pid: this makes complete sense for a Cell to isolate. it means the first executable spawned will be "pid 1" in the namespace.
* net: i think this also makes sense for a Cell, but it might mean having some API to open up ports between Cells.  it gives us some nice effects like assumption of eth0 in the Cell bridged to a virtual device in the Auraed space.
* mnt: unless we think Cells might want to share mount points, this makes complete sense to me.
* uts: i don't think we want this.. we want Cells to share the hosts hostname i believe.  it makes it easy to reason about things from the Cell's POV.
* ipc: /shrug :)
* user: some security benefit to using this (can make user 0 unprivileged, and map UIDs to the host

**Comment by krisnova** [comment]
Started this work in https://github.com/aurae-runtime/aurae/pull/178

**Comment by krisnova** [comment]
We need to do some research on how cgroup namespaces and the other namespaces correlate to each other. 

My PR https://github.com/aurae-runtime/aurae/pull/178 does the initial plumbing and new we need to start testing and validating our assumptions. I was not able to get the `ps aux` command to return the expected results for running in a new pid namespace.

We can (and should) look at a test harness of sorts for this!

**Comment by krisnova** [comment]
#183 also related

**Comment by krisnova** [comment]
I believe closed with #194
