### ISSUE TITLE
Transfer to PSL (Public Stewardship License) for The Nivenly Foundation

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#191]
The PSL releases the project to the public domain, and also includes the concept of a "steward" of the project. 

Can we please change the license from Apache 2.0 to the [PSL 1.0](https://github.com/softwarestewardship/license) and call out the **Nivenly Foundation** as our official steward?

We will need to update the CLA as well as have existing contributors to Aurae agree to the new terms.

**Comment by dmah42** [comment]
can we discuss this a bit first? it has potential implications for existing contributions and contributors that we should fully understand before making the change.

**Comment by krisnova** [comment]
Yes. Every contributor would need to be involved before we can make any changes. This would be what most managers would call "a very big deal". I would see it taking several weeks/months if it even happened at all. 

Just wanted to start the discussion. This change is intended to free/open up contributions more and not the opposite. If this is making it MORE difficult to contribute, than we will likely need to reevaluate.

**Comment by dmah42** [comment]
have you had any concerns raised that the Apache 2.0 license is making it difficult for individuals or representatives of corporations to contribute?

i ask because my particular situation make it very easy to contribute under the Apache 2.0 license, however public domain licenses (especially new ones) come under a great deal of scrutiny.

**Comment by dmah42** [comment]
@krisnova are you comfortable with the discussions we've had about this or would you like to continue discussing it?
