### ISSUE TITLE
Possible to destroy cgroups manually and Aurae still has them in cache

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#198]
Right now it is possible to use the `rmdir` command in the `/sys/fs/cgroup` directory to manually destroy cgroups. 

In the event that we manually destroy a cgroup that was started with `auraed` the internal cache still believes the cgroup exists. This is problematic when we try to re-create the cgroup again with `auraed`.

**Comment by future-highway** [comment]
Questions for how we want to handle cache reconciliation in the following scenarios:

1. Allocate Cell
    a. Cell does not exist in cache, but cgroup exists on fs (cgroup may have been made my other means)

2. Free Cell
    a. Cell exists in cache, but not on fs
    b. Cell does not exist in cache, but cgroup exists on fs

2a is the easiest to decide for. We can either respond with an error (CellNotFound) or respond with success since the outcome is the same (i.e., no cgroup)

1a/2b need more thoughtful consideration. Do we want a new error that indicates a conflict and the leave it to the user? Or do we want to do something else?

**Comment by dmah42** [comment]
opinions here, no decisions:

> Questions for how we want to handle cache reconciliation in the following scenarios:
> 
> 1. Allocate Cell
>     a. Cell does not exist in cache, but cgroup exists on fs (cgroup may have been made my other means)

is this always user error? 
 if in their script they don't free, this will happen the second time.  this shouldn't happen outside aurae as aurae is pid 1 :)

however it may be hard for a user to recover without a reboot... so we could also "adopt" the cgroup with a big fat warning. this feels uncomfortable too though.

I think error and link to some documentation on how to recover. maybe on aurae.io.

> 
> 2. Free Cell
>     a. Cell exists in cache, but not on fs
>     b. Cell does not exist in cache, but cgroup exists on fs
> 
> 2a is the easiest to decide for. We can either respond with an error (CellNotFound) or respond with success since the outcome is the same (i.e., no cgroup)

it must be a user error though.. double free or manual intervention.  maybe log a warning or error and continue?

but I prefer an error with explanation of we can.

> 
> 1a/2b need more thoughtful consideration. Do we want a new error that indicates a conflict and the leave it to the user? Or do we want to do something else?

2b is the same as 1a except it must be manual intervention (or two scripts running??).  either way, hard error I think.
