### ISSUE TITLE
Add "list" method

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#217]
We need a way to query the cache and list all known pods, containers, cells, and executables known to a specific auraed. 

If list works recursively we should be able to build a graph if we query the "root" auraed.

 - Introduce list method to runtime.proto and return a set of responses

**Comment by krisnova** [comment]
This is becoming more relevant.

We need to be able to "list" cells. See #308 where we introduce list pods style methods with the CRI. We should be able to mirror this functionality with Aurae cells and executables.

**Comment by JeroenSoeters** [comment]
@krisnova should we close this issue?
