### ISSUE TITLE
Aurae as a Hypervisor (Kubernetes Namespaces)

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#22]
Similar to #21 

## Does each Namespace get a VM?

More importantly **should** each namespace get a VM? 

How do we start to experiment with isolation primitives for Kubernetes? Even though Aurae will not have Kubernetes awareness, it should consider the scope of Kubernetes similar to the scope of Aurae. We just aim to standardize the components according to the #20 principle of least awareness.

**Comment by MalteJ** [comment]
I would prefer to create a (Micro-)VM for every pod.

We have a resource pool of multiple servers, each with a certain number of CPUs and RAM. I'd like to have a fine granular placement of workloads onto those servers. If you put multiple pods (of the same namespace) into one VM, you'd need to size the VM bigger than needed, as you have to plan for additional pods in the future.

Instead we could simply schedule pods to the servers and use VMs as a sandboxing mechanism. The scheduling mechanism would not take namespaces into consideration. It would just schedule according to ressource requirements. In the end this should result in a better ressource utilization.
