### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#231]
Hello. This issue is intended to serve as a design for how the Aurae project will (generally) manage 
versioning different sections of the codebase as well as the impact this design will have on sub-projects such as **AuraeScript** and **ae** and **aer**. 

## How will "Aurae be Versioned"? 

In short, the entire project will be versioned globally by [semantic versioning](https://semver.org/) and follow the **MAJOR.MINOR.PATCH** methodology. 

All binaries will be released with a global semantic versioning number.

For example `auraed v1.2.3` should be compatible with `auraescript v1.2.3`.
For example `ae v1.2.3` should not be compatible with any binary `v2.X.X` 

## What artifacts go into "an Aurae release"? 

 - `auraed` daemon binary
 - `ae` Go command line tool
 - `aer` Rust auto-generated command line client
 - `auarescript` Rust auto-generated binary

## What OS do we currently support?

 - Linux

## What architecture do we currently support?

 - X86

## How do we version the RPC services (standard library)?

We will use beautiful names to name give our RPCs unique and spoken identifiers similar to how [Hurricanes and Tropical Cyclones/Storms are named](https://www.nhc.noaa.gov/aboutnames_history.shtml). The author of each new API can chose whatever name they like as long as they feel it is a beautiful name, and it comes sequentially next in the English phonetic alphabet.  

The names serve as a way of breaking apart the APIs into incompatible layers, or what semver would refer to as a **Major Breaking Change**. 

Consider the following structure where `observe/alex` depends on the runtime subsystem.

```
.
├── observe
│   └── alex
│       ├── cells.proto
│       └── pods.proto
└── runtime
    ├── alice
    │   ├── cells.proto
    │   └── pods.proto
    └── beatrix
        ├── cells.proto
        └── pods.proto
```

Now imagine upgrading `runtime/alice` to `runtime/beatrix` internally in the code base.

It is possible to completely change the API surface from `runtime/alice` to `runtime/beatrix` without changing the API surface of `observe/alex` as `observe/alex` depends on runtime. 

We can continue to version the global architecture as we expose/break APIs that are exposed publicly without having to couple our services to numbers.

In general we want to keep our RPC services versioned in a way that does not use numbers or the greek alphabet as those have special meanings in other software projects. Using the hurricane name method, we can easily identify discreet packages which do not change their compatibility over time. We can easily map the services together and communicate about the services easily without introducing a confusing paradigm that "alpha" or "v0" needs to somehow be compatible with "beta" or "v2".

**Comment by RRethy** [comment]
> For example auraed v1.2.3 should be compatible with auraescript v1.2.3.
> For example ae v1.2.3 should not be compatible with any binary v2.X.X

I'm assuming we will expect `auraed v1.2.3` to be compatible with `auraescript v1.1.1`?

For RPC versioning:

- Would duplicate beautiful names be allowed across APIs? E.g. could we have `runtime/adam` and `observe/adam`?
- Are there any examples in the wild of projects which follow this type of naming?
- What would a compatibility issues look like across runtime/observe/schedule/etc. which this is trying to solve? Observe looks like it just takes IDs atm, I'm not clear on schedule, but if they have interconnectivity or dependance on a shared type then I'd lean towards having them in the same gRPC service instead of trying to maintain compatibility between message types across services.

I'm a bit confused on the beautiful names naming, not sure if I see the benefit over the common v0/v1/v2.

**Comment by krisnova** [comment]
So I want to be clear: There isn't really isn't much of a difference between a "beautiful name" and what most projects call `v0` or `v1` apis other than semantics. 

Let's imagine a fictional project called `widget` that just released `widget v1.2.3` to the public. Now imagine that `widget` had an API called `v1` somewhere inside the project. Say the API was called `/sprocket`. 

My confusion would arise when `widget v2.0.0` is released however for some reason I still need to understand what `/sprocket v1` is. Basically my thought here is that if we use versioning **numbers** as a way of identifying one system in the project (the semantic version), we shouldn't really use numbers again anywhere else as it might lead to confusion when these numbers randomly start/stop aligning with each other.

### Look at Kubernetes

A concrete example is Kubernetes. Take Kubernetes [Version 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25) for example.

In the `Kubernetes v1.25` release you have the following APIs:

 - autoscaling/v2
 - events.k8s.io/v1
 - batch/v1

and about a dozen or so `v1beta1`'s and `v1alpha1`'s and `v1beta2`'s etc, etc...

Basically what I am saying is that I am confused and frustrated as a user that for some reason I need to care that "Kubernetes is v1.25" however my "Autoscaling is v2" and "Batch is v1" and so on. 

I don't want to have to be explaining to people that the numbers mean different things in different places, so I figured we should just scrap using numbers altogether for the lower level API packaging. 

### Answering your questions

> I'm assuming we will expect auraed v1.2.3 to be compatible with auraescript v1.1.1?

Yes. I think in theory yes that would/should work however we should probably advertise that best practices say to keep all components the same version. I understand that won't be possible as people will write AuraeScript and leave it sitting on a server, however we can do the best we can and leave the breaking changes to the major version numbers. 

> Would duplicate beautiful names be allowed across APIs? E.g. could we have runtime/adam and observe/adam?

No. We follow hurricane rules which to me means that you don't repeat names. Each API should have a unique name that lives independently and grows independently. I know it seems stupid but honestly take a look at how quickly Kubernetes grew and remind yourself that all of the `v1beta1`'s have absolutely nothing to do with each other. They may or may not be compatible at any time.

> Are there any examples in the wild of projects which follow this type of naming?

Look at [Ubuntu releases](https://en.wikipedia.org/wiki/Ubuntu_version_history) where semantic versioning is relatively lost. Basically there is a beautiful name associated with each version that doesn't really mean anything other than representing a static and repeatable distribution at a single time. We would effectively be doing the same thing. 

> What would a compatibility issues look like across runtime/observe/schedule/etc

There would be no assumptions here, which frankly is the point. 

`observe/adam` could depend on `runtime/zena` if we decided that was what made since for a specific version of Aurae. 

### Reminder that the names are just so we can manage translations 

At some point we need to be able to deterministically translate old APIs into new APIs. That is really all the names are for. As we evolve `runtime/alice` into `runtime/bob` we also write the conversion method `alice_to_bob(cell) -> cell` and `bob_to_alice(cell) -> cell` such that old APIs still produce roughly the same outcome. Even if the RPC server rejects the request we can at least have a way of taking an old client and translating it to the new API. 

### Disclaimer: I really don't care 

In general I have weak opinions on this. I understand this all sounds a bit ridiculous and frankly I just want it to be simple and elegant. If we can get away with `v0` and `v1` without introducing a lot of complexity and translation logic then I am convinced we should just do that. 

The beautiful names are a proposed way of getting our future selves out of the "here is why v1 in this API has nothing to do with v1 in that API both of which have nothing to do with V1.0.0 of the project" conversations.

**Comment by krisnova** [comment]
Note: I think the confusion in Kubernetes could also have more to do with how drunk on APIs the project became. 

I would hope that we practice slightly more reasonable self control, and realize that instead of flexibility and more APIs we offer a thoughtful opinion instead. Basically I don't want Aurae to end up creating too many services other than the original 8 or so we called out in the [whitepaper](https://docs.google.com/document/d/1dA591eipsgWeAlaSwbYNQtAQaES243IIqXPAfKhJSjU/edit#bookmark=id.5fk5pocac3op)

**Comment by dmah42** [comment]
do we need the inner names?  if we have aurae v1.2.3 as a release in GitHub, with generated protos and built binaries, we can just work at head internally across all the APIs I think.

this might mean we need a single proto for all the APIs but we can I think keep them separate and import them (maybe import public).  I'm not sure what this does to client code or bloat.

**Comment by future-highway** [comment]
The names confuse me, but I'm also not great with remembering names, so maybe that's part of the problem. However, I understand that it solves the issue of explaining why v2 is or isn't compatible with v1. But, does that mean we need to remember the 8 names aurae v2 is compatible with? Is that better?

**Comment by krisnova** [comment]
I made a decision.

Let's go with the "normal" `v0` and `v1` style pattern and give up on beautiful/hurricane names. 

We can version at the service level and we can just offer a page in our docs that explain why `runtime.v0` doesn't necessarily need to correspond to `observe.v0` and so on. When folks are inevitably confused we can just fire the blog post at them at hope for the best.
