### ISSUE TITLE
Introduce Signal API

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#237]
Can we please add an API to expose POSIX signals metadata using Aurae? 

This will be helpful for a few reasons, notably:

 - It gives us a reason to "plumb" an eBPF loader/unloader framework into Aurae. 
 - It gives us the ability to offer observability remotely on POSIX signals

**Comment by krisnova** [comment]
See the `signals-ebpf` probe for more context: https://github.com/ricardomaraschini/ebpf-signals

**Comment by JeroenSoeters** [comment]
Is this something we would want to add to the `Observe` API?

**Comment by dmah42** [comment]
yes

**Comment by JeroenSoeters** [comment]
Looking at: https://github.com/ricardomaraschini/ebpf-signals/blob/main/signals-ebpf/src/main.rs#L15 and wondering why I never noticed those `format` files before 😭 This means - at least for this first cut - we don't need to rely on BTF symbols to be available on the host? We would require `debugfs` to be mounted, though.

(assuming here we want to ship pre-compiled eBPF programs)

**Comment by JeroenSoeters** [comment]
Should we close this one?
