### ISSUE TITLE
Application kernel for Aurae VMs

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#238]
Do we want to start talking about requirements for which kernel we ship with our VMs?

Right now we are using a [stock Linux 5.15 kernel](https://github.com/aurae-runtime/aurae/blob/main/auraed/hack/kernel/config.sh#L33-L34)

Maybe its time to start talking about tightening this service up and building out the API in rust?

I think looking at [gvisor](https://github.com/google/gvisor) could be worth our time.

**Comment by MalteJ** [comment]
We will implement a release strategy, that includes a decision on the Linux Kernel version.
