### ISSUE TITLE
cgroup.rs is not passing period

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#262]
See https://github.com/aurae-runtime/aurae/blob/main/auraed/src/runtime/cell_service/cells/cgroups/cgroup.rs#L57

```rusT
        let inner = CgroupBuilder::new(&name)
            // CPU Controller
            .cpu()
            .shares(cpu_weight.into_inner())
            .mems(cpuset_mems.into_inner())
            .period(1000000) // microseconds in a second
            .quota(cpu_quota.into_inner())
            .cpus(cpu_cpus.into_inner())
            .done()
            // Final Build
            .build(hierarchy);
```

Right now the period is set to 1000000 which should be passed in from the API and not hard coded.

**Comment by dmah42** [comment]
no this is deliberate.  the cgroup period acts as a demoninator for the quota. I hard coded it to this so the quota can be in sensible consistent units of "share of a second".

this is not a bug.  I should document this though.

**Comment by krisnova** [comment]
Maybe make it a constant and add the docs above the constant declaration inline?
