### ISSUE TITLE
Switch to Youki cgroup driver

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#290]
We should consider going "all in" on youki for our cgroups and container runtime.

There is a cgroup library https://github.com/containers/youki/tree/main/crates/libcgroups that we can replace our current dependency with.

I am in the process of contributing some example code to the youki project now that we can use here in Aurae.

**Comment by krisnova** [comment]
This will likely require libdbus unless somebody goes and patches youki like we did with libcontainer

**Comment by dmah42** [comment]
I think @future-highway just did this

**Comment by yihuaf** [comment]
Using `libcgroup` feature `v2` with `no-default-features` should remove libdbus from the dependency. Let me know if there is any other issue or file an issue on youki directly. I can help pick up any work.

**Comment by dmah42** [comment]
i believe this is now resolved and we're happily using youki
