### ISSUE TITLE
Bi-weekly meetings

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#355]
Do we want to start scheduling bi-weekly open calls for the Aurae community to help establish a roadmap? 

Please vote on your preferred time for a 1 hour meeting below by adding the following to the options in comments below.

 - 👍🏻 Yes, this is preferred for me
 - Leave empty for no preference
 - 👎🏻 No, I will not attend if you schedule at this time

All meetings would start the week of February 13th, and repeat **every other week** according to a published calendar.

**Comment by krisnova** [comment]
Mondays (8:00am Pacific) (16:00 UTC)

**Comment by krisnova** [comment]
Tuesdays (8:00am Pacific) (16:00 UTC)

**Comment by krisnova** [comment]
Wednesdays (8:00am Pacific) (16:00 UTC)

**Comment by krisnova** [comment]
Thursdays (8:00am Pacific) (16:00 UTC)

**Comment by krisnova** [comment]
Fridays (8:00am Pacific) (16:00 UTC)

**Comment by MalteJ** [comment]
We will revisit this
