### ISSUE TITLE
Remove `aurae` prefixes

### ISSUE THREAD

**Issue by jesse-peters** [aurae-runtime/aurae#371]
We currently use the `aurae` prefix on our folders. We should remove those since that's implied by the fact that they're in the ` aurae` repository.

Below it should read:
`client`
`proto`

<img width="210" alt="image" src="https://user-images.githubusercontent.com/3060031/217294126-bb641f15-ee50-4826-adb9-0c72862afd89.png">

**Comment by dmah42** [comment]
working on proto now. I'll leave that as an example if someone wants to do client.

**Comment by dmah42** [comment]
does aurae-client make sense as a published crate?  i thought with auraed, auraescript, and aer we were covered.

**Comment by krisnova** [comment]
I believe this is now closed. Very important to see my note in https://github.com/aurae-runtime/aurae/pull/372#issuecomment-1426829805
