### ISSUE TITLE
Do not hard code "/var/run/aurae" and similar values in nested crates

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#373]
All of the nested crates and packages in auraed should be respecting the values in `lib.rs` and building on them.

See the `auraed/src/lib.rs` file and grep for `/var/lib/aurae` and `/var/run/aurae`.

Basically we should have a single constant at the top of `lib.rs` with the root folder, and everything else should build off of that constant. 

A further issue would be to add command line flags to override this value at runtime.

**Comment by tlaferriere** [comment]
Hi! I created a draft PR of one changed for early feedback if necessary. I will be continuing this one file at time. It appears mostly to be trivial path joins, so I don't expect there to be much to decide about (such as adding a dependency).
