### ISSUE TITLE
Bypass services that depend on eBPF when probe is missing

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#381]
In the event that a service depends on a given eBPF probe to be loaded at runtime, we should simply skip trying to load the service at the daemon bootstrapping phase, instead of halting the program.

CC @JeroenSoeters

**Comment by JeroenSoeters** [comment]
I think we can just log an error in case we are not able to load the probe. In the future, we could add a startup flag to disable eBPF (or specific probes) and not attempt to load the probes altogether (if that makes sense for users to do). We would just need to come up with sensible gRPC status codes to return for the endpoints that rely on eBPF.
