### ISSUE TITLE
Clone init::Context into AuraeRuntime

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#384]
Right now we are using the `nested` flag in the `AuraeRuntime` struct to determine if Aurae is being ran as "nested".

Can we please clone/copy the entire `init::Context` enum up into the main runtime daemon code such that we can use it for other decisions in the code path? This will be helpful for determining if we want to switch on eBPF loading or not.

For example: We do not want to load eBPF probes in containers, as they will already be loaded by the host.

**Comment by krisnova** [comment]
CC @JeroenSoeters

**Comment by JeroenSoeters** [comment]
See: https://github.com/aurae-runtime/aurae/pull/386
