### ISSUE TITLE
Implement Cache for CRI

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#385]
Right now the CRI service code is blocked on adding a caching mechanism to the code base (similar to what we have [done with cells](https://github.com/aurae-runtime/aurae/blob/main/auraed/src/cells/cell_service/cell_service.rs)).

Can we please add the get/set cache code into the `cri_service.rs` file in place of the existing todo's?

For example in order for us to stop a pod sandbox:

```rust 
    async fn stop_pod_sandbox(
        &self,
        _request: Request<StopPodSandboxRequest>,
    ) -> Result<Response<StopPodSandboxResponse>, Status> {
        // TODO: Pull sandbox from cache
        // TODO: sandbox.kill()
        todo!()
    }
```

We need to first have the cached pod sandbox available, then we can call `sandbox.kill()` on the item retrieved from the cache.

**Comment by krisnova** [comment]
CC @dmah42

**Comment by dmah42** [comment]
which branch are you working on that has the TODOs?

**Comment by dmah42** [comment]
i think i found it on main

**Comment by dmah42** [comment]
there are some nuances here that i'd like to get clarity on:

1. the high level object is a `PodSandbox` with lower level `Container` objects.  right now, the thing called a "sandbox" is actually a `Container`.  so should the cache be at the container level or the pod sandbox level?
2. we use both `libcontainer::container` and `aurae_proto::cri`, which define things like `ContainerStatus` for example.  should we be mapping between them or is this unexpected?

**Comment by krisnova** [comment]
@dmah42 hopefully you saw my comment: https://github.com/aurae-runtime/aurae/pull/388#discussion_r1103509601

I might push some changes to your branch today if i can find the time/energy
