### ISSUE TITLE
Utilize `deno_runtime::MainWorker` to enable more Deno features when running AuraeScript files

### ISSUE THREAD

**Issue by seanwatters** [aurae-runtime/aurae#434]
Currently AuraeScript is only using the `deno_core::JsRuntime` to run AuraeScript files, which only provides core Deno functionality. In order to enable additional Deno features like Web APIs, IO, file system access, HTTP (which should all be safe to enable if AuraeScript files are only being executed on the user's machine) we can use the `deno_runtime::MainWorker` struct which bakes all of the corresponding native ops and js files needed for those to work. 

Currently switching to `deno_runtime::MainWorker` is blocked due to a lock on `uuid` version `=1.1.2` in the Deno workspace. A PR for unlocking and upgrading the `uuid` version has been approved and merged (https://github.com/denoland/deno/pull/17963), but currently waiting on a new publish for the crate.

EDIT:

Will submit a PR with the AuraeScript change once the changes to the `deno_runtime` crate are published.

**Comment by GANitak** [comment]
Thanks for the addition of deno_runtime::MainWorker 
This will help a lot

I’ve seen the PR approved for the uuid version 1.3.0 feature of v4 :)
