### ISSUE TITLE
 libcontainer dependency was updated and our cargo.toml is only pinned to the branch, not the commit

### ISSUE THREAD

**Issue by GANitak** [aurae-runtime/aurae#467]
MAIN branch :

 * cargo.lock has a commit hash `cc2a4d0fdd5d7f2c05a218322a0c8bfd0ea22fdf` 
 -> not on the branch (musl-libcontainer)

Changing the hash to in cargo.toml : 
`0836dbf2fa358d66e026b321f3d44c636b89091f` create a new error : 

 >   Checking libcontainer v0.0.4 (https://github.com/krisnova/youki?branch=musl-libcontainer#cc2a4d0f)
error[E0308]: mismatched types
   --> /home/ganitak/.cargo/git/checkouts/youki-ecf4771dd4ac50dc/cc2a4d0/crates/libcontainer/src/process/container_intermediate_process.rs:147:17
    |
147 |                 resources,
    |                 ^^^^^^^^^ expected struct `oci_spec::runtime::linux::LinuxResources`, found struct `LinuxResources`
    |
    = note: struct `LinuxResources` and struct `oci_spec::runtime::linux::LinuxResources` have similar names, but are actually distinct types
note: struct `LinuxResources` is defined in crate `oci_spec`
   --> /home/ganitak/.cargo/registry/src/github.com-1ecc6299db9ec823/oci-spec-0.5.8/src/runtime/linux.rs:654:1
    |
654 | pub struct LinuxResources {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^
note: struct `oci_spec::runtime::linux::LinuxResources` is defined in crate `oci_spec`
   --> /home/ganitak/.cargo/registry/src/github.com-1ecc6299db9ec823/oci-spec-0.6.0/src/runtime/linux.rs:658:1
    |
658 | pub struct LinuxResources {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `oci_spec` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `libcontainer` due to previous error
make: *** [Makefile:235: auraed-lint] Error 101

I am guessing there is more to change...

On going

**Comment by yihuaf** [comment]
I can help fixing this.

**Comment by yihuaf** [comment]
I believe this is resolved in #483 now.

**Comment by bpmooch** [comment]
@dmah42 close this yea?

**Comment by dmah42** [comment]
yes!
