### ISSUE TITLE
SPDX License Identifiers in the Source Code

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#468]
Folks might consider vendoring small crates and modules from the Aurae source code.

Can we please add SPDX license identifiers **to every .rs file in the project**?

For more on using the SPDX in source code read [the SPDX tutorial](https://github.com/david-a-wheeler/spdx-tutorial/blob/master/README.md#spdx-license-expressions-in-source-code-files).

Basically I think we just need to use this and fill in the blanks in each of our headers.

```
# Copyright [year file created] - [last year file modified], [project founder] and the [project name] contributors
# SPDX-License-Identifier: [SPDX license expression]
```

**Comment by MalteJ** [comment]
Can we then maybe also reduce this huuuuuge license header in our source code files to the legally required minimum?
CC: @dmah42

**Comment by dmah42** [comment]
fun fact: there is no legally required minimum that i know about. the package has a license and copyright statement.  it is true that someone might want to vendor parts of the source code but i'm not sure how a header in a source file stops them/encourages them doing it.

the current header was a deliberate choice and preference by Nóva and is very much her personal style.

**Comment by bpmooch** [comment]
```
# ---------------------------------------------------------------------------- #
#                +--------------------------------------------+                #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
# ---------------------------------------------------------------------------- #
# Copyright 2022 - 2024, [project founder] and the aurae contributors
# SPDX-License-Identifier: Apache-2.0
```

is this a little better?

**Comment by dmah42** [comment]
it's about 18 lines better i think :D

**Comment by dmah42** [comment]
i'm starting to edit headers as i edit files.
