### ISSUE TITLE
Custom Language Support: VSCode Extensions

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#67]
Similar to #66 can we please implement a [VScode language extension](https://code.visualstudio.com/api/language-extensions/overview) for AuraeScript?

It will need to read from the [lib.rs](https://github.com/aurae-runtime/aurae/blob/main/auraescript/src/lib.rs) source of truth for the language.

See also #63

**Comment by hazelweakly** [comment]
As a start, if AuraeScript were to build a few things first, it would be able to implement language extensions much quicker for a wide variety of editors:

- treesitter support for the syntax and grammar
  - directly usable by neovim, emacs, and other editors. Gives you quite a few things beyond just syntax highlighting
- LSP client for auraescript
  - integration to VSCode, neovim, emacs, etc., become trivial (plugins are essentially optional at that point. VSCode still needs one but it becomes a shell plugin of majority boilerplate)
  - If designed a certain way, extracting out `format`, and `lint` functionality into sub-commands/CLI-tools becomes nearly free, effort wise.

There's more, but those two are already a large effort. As an aside, it would be potentially useful to think about what AuraeScript should do from a holistic viewpoint and see what sorts of more novel tooling would be very useful to facilitate higher level goals that people have when writing it.

As an example, here's some "cool" less general-purpose tooling that makes sense for their respective communities:

- [zig as a replacement for CC](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html)
- [pharo for smalltalk is very interesting in terms of being novel yet highly tuned to its environment](https://www.youtube.com/watch?v=baxtyeFVn3w)
- [AST Explorer for javascript and typescript](https://astexplorer.net/)
