### ISSUE TITLE
Destroy branches on merge

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#80]
I believe this is a github setting we need to investigate

**Comment by sidpalas** [comment]
Should be: `Settings > Pull Requests > Automatically delete head branchs`

Here are the relevant docs!

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by dominichamon** [comment]
i enabled this a little while ago.
