### ISSUE TITLE
Speed up compiles

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#81]
Is there any way we can make optimizations in the Aurae compile time? How many dependencies are we building that we are no longer using? How about caching and optimization?

**Comment by dashall** [comment]
overall the compile times are good. 
did some test with [sscache](https://github.com/mozilla/sccache) on i5-4590 CPU @ 3.30GHz

make (no sscache)
```
real	4m56.432s
user	10m14.189s
sys	0m53.258s
```

make (with sscache)
```
real	6m48.979s
user	2m44.771s
sys	0m26.258s
```
2nd run (sscache)
```
real	5m6.521s
user	2m43.050s
sys	0m26.101s
```

on optimization

```
[Number one optimization tip: don't](https://gist.github.com/jFransham/369a86eff00e5f280ed25121454acec1#number-one-optimization-tip-dont)
```

**Comment by dmah42** [comment]
closing this in favour of #461 which has more detail
