### ISSUE TITLE
Monitoring (more 404s) on the website 

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#82]
How do we know if our site as down? 

Right now [aurae.io](https://aurae.io) is offline and is returning a 404. 

Can we alert our discord and let the maintainers know when the site is broken?

**Comment by hazelweakly** [comment]
A downdetector-like service combined with a discord bot would accomplish both tasks. I looked briefly and don't seem to find any bots that do this out-of-the-box, but writing one isn't _particularly_ hard for this functionality iirc.

**Comment by krisnova** [comment]
So @taniwha3 has set one up for us for other non-aurae projects/infrastructure that our crew hosts. I believe we use [uptime robot](https://uptimerobot.com/). Unsure if someone can set it up for free? 

Also we have a working Kubernetes cluster available to our project as well. In event somebody wants to get creative with prometheus or similar.
