### ISSUE TITLE
Aurae Official Blog

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#83]
Can we host an official project blog on the website? I'd like to move some of my articles over to the project to use as needed. 

Also as we identify new paradigms such as Aurae Cells and Aurae Pods we likely will need to do some story telling.

**Comment by orzen** [comment]
They released a blog plugin for the material mkdocs in September, however it's only available for sponsors(paying in some way) of the project. I don't know if we want to invest in material mkdocs or if we want to setup something separate?

Here's the link to the material mkdocs plugin if you want to take a look at it: https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/
